[Rainmeter]
Update=-1
OnRefreshAction=[!HideMeterGroup Config][!Update]
SkinWidth=#SCREENAREAWIDTH#
SkinHeight=#SCREENAREAHEIGHT#

[Metadata]
Name=WallpaperCube
Author=EverMeme
Information=Hover on the Box to show setting. Enable "Click through" after finished configuration to prevent setting tab showing.
Version=1.0
License=CC BY-NC-SA 4.0

[Variables]
FrameSizeX=462
FrameSizeY=845
FramePosX=441
FramePosY=133
PicPosX=300
PicPosY=95
PicSize=0.87
FrameWidth=5
FrameColor=220,220,220,255
ShadowColor=127,127,127,0
ShadowOffset=5

;; --- Picture Path ---
BGN_Path=#@#default.jpg
BGN_Path_display=default.jpg

;; --- Real-time state variables ---
X = 0
Y = 0
buffer_X=0
buffer_Y=0

;; --- Main Measures ---
[measureBuffer]
Measure=Plugin
Plugin=Mouse
MouseMoveAction=[!SetVariable "buffer_X" $MouseX$][!SetVariable "buffer_Y" $MouseY$][!Update]
RelativeToSkin=0
RequireDragging=0
DynamicVariables=1

[MeasureMouseFrameSize]
Measure=Plugin
Plugin=Mouse
LeftMouseDownAction=[!SetVariable "X" $MouseX$][!SetVariable "Y" $MouseY$][!Update]
LeftMouseDragAction=[!SetVariable "X" $MouseX$][!SetVariable "Y" $MouseY$][!SetVariable FrameSizeX "(Clamp([MeasureScriptX:],150,#SCREENAREAWIDTH#))"][!SetVariable FrameSizeY "(Clamp([MeasureScriptY:],150,#SCREENAREAHEIGHT#))"][!Update]
LeftMouseUpAction=[!CommandMeasure MeasureScriptX "End()"][!CommandMeasure MeasureScriptY "End()"][!CommandMeasure MeasureMouseFrameSize "Stop"][!Update]
RelativeToSkin=0
RequireDragging=1
DynamicVariables=1

[MeasureMouseFramePosition]
Measure=Plugin
Plugin=Mouse
LeftMouseDownAction=[!SetVariable "X" $MouseX$][!SetVariable "Y" $MouseY$][!Update]
LeftMouseDragAction=[!SetVariable "X" $MouseX$][!SetVariable "Y" $MouseY$][!SetVariable FramePosX "(Clamp([MeasureScriptX:],0,#SCREENAREAWIDTH#))"][!SetVariable FramePosY "(Clamp([MeasureScriptY:],0,#SCREENAREAHEIGHT#))"][!Update]
LeftMouseUpAction=[!CommandMeasure MeasureScriptX "End()"][!CommandMeasure MeasureScriptY "End()"][!CommandMeasure MeasureMouseFramePosition "Stop"][!Update]
RelativeToSkin=0
RequireDragging=1
DynamicVariables=1

[MeasureMousePicturePosition]
Measure=Plugin
Plugin=Mouse
LeftMouseDownAction=[!SetVariable "X" $MouseX$][!SetVariable "Y" $MouseY$][!Update]
LeftMouseDragAction=[!SetVariable "X" $MouseX$][!SetVariable "Y" $MouseY$][!SetVariable PicPosX "[MeasureScriptX:]"][!SetVariable PicPosY "[MeasureScriptY:]"][!Update]
LeftMouseUpAction=[!CommandMeasure MeasureScriptX "End()"][!CommandMeasure MeasureScriptY "End()"][!CommandMeasure MeasureMousePicturePosition "Stop"][!Update]
RelativeToSkin=0
RequireDragging=1
DynamicVariables=1

[MeasureScriptX]
Measure=Script
ScriptFile=#@#Scripts\DragManagerX.lua

[MeasureScriptY]
Measure=Script
ScriptFile=#@#Scripts\DragManagerY.lua

[DragNDrop]
Measure=Plugin
Plugin=Drag&Drop
Action=Path
OnDropAction=[!SetVariable "BGN_Path" $File$][!SetVariable "BGN_Path_display" $Name$.$Type$][!Update]

[MeasureUserInputNumbers]
Measure=Plugin
Plugin=InputText
SolidColor=76A0E8FF
FontColor=255,255,255,255
FontFace=Consolas
StringStyle=Italic
FontSize=14
InputNumber=1
DefaultValue=1
X=15
Y=400
H=20
W=330
Command1=[!SetVariable FrameSizeX (Clamp($UserInput$,150,#SCREENAREAWIDTH#))][!Update]
Command2=[!SetVariable FrameSizeY (Clamp($UserInput$,150,#SCREENAREAHEIGHT#))][!Update]
Command3=[!SetVariable FramePosX (Clamp($UserInput$,0,#SCREENAREAWIDTH#))][!Update]
Command4=[!SetVariable FramePosY (Clamp($UserInput$,0,#SCREENAREAHEIGHT#))][!Update]
Command5=[!SetVariable PicPosX $UserInput$][!Update]
Command6=[!SetVariable PicPosY $UserInput$][!Update]
Command7=[!SetVariable PicSize (Clamp($UserInput$,0.1,2))][!Update]
Command8=[!SetVariable FrameWidth (Clamp($UserInput$,0,20))][!Update]
Command9=[!SetVariable ShadowOffset (Clamp($UserInput$,0,20))][!Update]

[MeasureUserInputColor]
Measure=Plugin
Plugin=InputText
SolidColor=76A0E8FF
FontColor=255,255,255,255
FontFace=Consolas
StringStyle=Italic
FontSize=14
X=15
Y=400
H=20
W=330
Command1=[!SetVariable FrameColor $UserInput$][!Update]
Command2=[!SetVariable ShadowColor $UserInput$][!Update]

;; --- Display ---
[MeterShadow]
X=(#FramePosX# + #ShadowOffset#)
Y=(#FramePosY# + #ShadowOffset#)
Meter=Shape
Shape=Rectangle 0,0,#FrameSizeX#,#FrameSizeY# | FillColor 0,0,0,1 | StrokeWidth #FrameWidth# | Stroke Color #ShadowColor#
DynamicVariables=1

[Meter_Container]
X=#FramePosX#
Y=#FramePosY#
Meter=Shape
Shape=Rectangle 0,0,#FrameSizeX#,#FrameSizeY# | FillColor 255,255,255
DynamicVariables=1

[Meter_Container_Preview]
Meter=Shape
Shape=Rectangle 0,0,#SCREENAREAWIDTH#,#SCREENAREAHEIGHT# | FillColor 255,255,255,127
DynamicVariables=1

[Picture]
X=(-1*#FramePosX# + #PicPosX#)
Y=(-1*#FramePosY# + #PicPosY#)
Meter=Image
ImageName=#BGN_Path#
H=(#SCREENAREAHEIGHT#*#PicSize#)
PreserveAspectRatio=1
Container=Meter_Container
DynamicVariables=1

[Picture_Preview]
X=#PicPosX#
Y=#PicPosY#
Meter=Image
ImageName=#BGN_Path#
H=(#SCREENAREAHEIGHT#*#PicSize#)
PreserveAspectRatio=1
Container=Meter_Container_Preview
LeftMouseDownAction=[!CommandMeasure MeasureMousePicturePosition "Start"][!CommandMeasure MeasureScriptX "StartPicturePosition()"][!CommandMeasure MeasureScriptY "StartPicturePosition()"][!Update]
MouseScrollUpAction=[!SetVariable PicSize "(Clamp(#PicSize#+0.01,0.1,2))" ][!Update]
MouseScrollDownAction=[!SetVariable PicSize "(Clamp(#PicSize#-0.01,0.1,2))" ][!Update]
Group=Config
DynamicVariables=1

;; --- Setting Tab ---
[MeterSettingTabBackground]
Meter=Shape
Shape=Rectangle 5,5,400,430 | StrokeWidth 2 | FillColor 127,127,150,100
DynamicVariables=1
Group=Config

[MeterSettingTabInfo]
X=8
Y=8
Meter=String
FontFace=Consolas
FontSize=14
AntiAlias=1
FontWeight=600
Text="[] #BGN_Path_display#"
DynamicVariables=1
Group=Config

[MeterSettingTabFrameWidth]
X=r
Y=R
Meter=String
FontFace=Consolas
FontSize=14
AntiAlias=1
Text="| Display Box:#CRLF#|   > Width: #FrameSizeX#"
SolidColor=0,0,0,1
LeftMouseDownAction=[!CommandMeasure "MeasureUserInputNumbers" "ExecuteBatch 1"]
DynamicVariables=1
Group=Config

[MeterSettingTabFrameHeight]
X=r
Y=R
Meter=String
FontFace=Consolas
FontSize=14
AntiAlias=1
Text="|   > Height: #FrameSizeY#"
SolidColor=0,0,0,1
LeftMouseDownAction=[!CommandMeasure "MeasureUserInputNumbers" "ExecuteBatch 2"]
DynamicVariables=1
Group=Config

[MeterSettingTabFrameXpos]
X=r
Y=R
Meter=String
FontFace=Consolas
FontSize=14
AntiAlias=1
Text="|   > X offset: #FramePosX#"
SolidColor=0,0,0,1
LeftMouseDownAction=[!CommandMeasure "MeasureUserInputNumbers" "ExecuteBatch 3"]
DynamicVariables=1
Group=Config

[MeterSettingTabFrameYpos]
X=r
Y=R
Meter=String
FontFace=Consolas
FontSize=14
AntiAlias=1
Text="|   > Y offset: #FramePosY#"
SolidColor=0,0,0,1
LeftMouseDownAction=[!CommandMeasure "MeasureUserInputNumbers" "ExecuteBatch 4"]
DynamicVariables=1
Group=Config

[MeterSettingTabPicXpos]
X=r
Y=R
Meter=String
FontFace=Consolas
FontSize=14
AntiAlias=1
Text="| Picture:#CRLF#|   > X offset: #PicPosX#"
SolidColor=0,0,0,1
LeftMouseDownAction=[!CommandMeasure "MeasureUserInputNumbers" "ExecuteBatch 5"]
DynamicVariables=1
Group=Config

[MeterSettingTabPicYpos]
X=r
Y=R
Meter=String
FontFace=Consolas
FontSize=14
AntiAlias=1
Text="|   > Y offset: #PicPosY#"
SolidColor=0,0,0,1
LeftMouseDownAction=[!CommandMeasure "MeasureUserInputNumbers" "ExecuteBatch 6"]
DynamicVariables=1
Group=Config

[MeterSettingTabPicSize]
X=r
Y=R
Meter=String
FontFace=Consolas
FontSize=14
AntiAlias=1
Text="|   > Size: #PicSize#"
SolidColor=0,0,0,1
LeftMouseDownAction=[!CommandMeasure "MeasureUserInputNumbers" "ExecuteBatch 7"]
DynamicVariables=1
Group=Config

[MeterSettingTabFrameStrokeWidth]
X=r
Y=R
Meter=String
FontFace=Consolas
FontSize=14
AntiAlias=1
Text="| Frame#CRLF#|   > StrokeWidth: #FrameWidth#"
SolidColor=0,0,0,1
LeftMouseDownAction=[!CommandMeasure "MeasureUserInputNumbers" "ExecuteBatch 8"]
DynamicVariables=1
Group=Config

[MeterSettingTabFrameStrokeColor]
X=r
Y=R
Meter=String
FontFace=Consolas
FontSize=14
AntiAlias=1
Text="|   > StrokeColor: #FrameColor#"
SolidColor=0,0,0,1
LeftMouseDownAction=[!CommandMeasure "MeasureUserInputColor" "ExecuteBatch 1"]
DynamicVariables=1
Group=Config

[MeterSettingTabFrameShadowColor]
X=r
Y=R
Meter=String
FontFace=Consolas
FontSize=14
AntiAlias=1
Text="|   > ShadowColor: #ShadowColor#"
SolidColor=0,0,0,1
LeftMouseDownAction=[!CommandMeasure "MeasureUserInputColor" "ExecuteBatch 2"]
DynamicVariables=1
Group=Config

[MeterSettingTabFrameShadowOffset]
X=r
Y=R
Meter=String
FontFace=Consolas
FontSize=14
AntiAlias=1
Text="|   > ShadowOffset: #ShadowOffset#"
SolidColor=0,0,0,1
LeftMouseDownAction=[!CommandMeasure "MeasureUserInputNumbers" "ExecuteBatch 9"]
DynamicVariables=1
Group=Config

[MeterSettingTabCloseSetting]
X=r
Y=R
Meter=String
FontFace=Consolas
FontSize=14
FontWeight=800
FontColor=184,2,2
AntiAlias=1
Text="[] Close Setting Tab & Save"
InlineSetting=Underline
SolidColor=0,0,0,1
DynamicVariables=1
Group=Config
LeftMouseDownAction=[!HideMeterGroup Config][!WriteKeyValue Variables BGN_Path #BGN_Path#][!WriteKeyValue Variables BGN_Path_display #BGN_Path_display#][!WriteKeyValue Variables FrameSizeX #FrameSizeX#][!WriteKeyValue Variables FrameSizeY #FrameSizeY#][!WriteKeyValue Variables FramePosX #FramePosX#][!WriteKeyValue Variables FramePosY #FramePosY#][!WriteKeyValue Variables PicPosX #PicPosX#][!WriteKeyValue Variables PicPosY #PicPosY#][!WriteKeyValue Variables PicSize #PicSize#][!WriteKeyValue Variables FrameWidth #FrameWidth#][!WriteKeyValue Variables FrameColor #FrameColor#][!WriteKeyValue Variables ShadowColor #ShadowColor#][!WriteKeyValue Variables ShadowOffset #ShadowOffset#][!Update]

[MeterFrame]
X=#FramePosX#
Y=#FramePosY#
Meter=Shape
Shape=Rectangle 0,0,#FrameSizeX#,#FrameSizeY# | FillColor 0,0,0,1 | StrokeWidth #FrameWidth# | Stroke Color #FrameColor#
LeftMouseUpAction=[!ShowMeterGroup Config][!Update]
DynamicVariables=1

;; --- Size Control ---
[MeterSizeControl]
X=#FramePosX#
Y=#FramePosY#
Meter=Shape
Shape=Rectangle (#FrameSizeX# - 36),(#FrameSizeY# - 36),36,36 | FillColor 127,0,0,127
LeftMouseDownAction=[!CommandMeasure MeasureMouseFrameSize "Start"][!CommandMeasure MeasureScriptX "StartFrameSize()"][!CommandMeasure MeasureScriptY "StartFrameSize()"][!Update]
Group=Config
DynamicVariables=1

;; --- Position Control ---
[MeterPositionControl]
X=#FramePosX#
Y=#FramePosY#
Meter=Shape
Shape=Rectangle (#FrameSizeX#/2 - 18),(#FrameSizeY#/2 - 18),36,36 | FillColor 0,127,127,127
LeftMouseDownAction=[!CommandMeasure MeasureMouseFramePosition "Start"][!CommandMeasure MeasureScriptX "StartFramePos()"][!CommandMeasure MeasureScriptY "StartFramePos()"][!Update]
Group=Config
DynamicVariables=1
